/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Profiler */

#ifndef _Included_Profiler
#define _Included_Profiler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Profiler
 * Method:    totalProcessVirtualMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Profiler_totalProcessVirtualMemory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
